CREATE DATABASE Enterprice;

CREATE TABLE Products
(
	Id INT PRIMARY KEY IDENTITY(1,1), 
	Name VARCHAR(150) NOT NULL,
	Price NUMERIC(10,2)
);

CREATE TABLE Clients
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	FirstName VARCHAR(40) NOT NULL,
	LastName VARCHAR(60) NOT NULL,
	City VARCHAR(50) NOT NULL,
	Phone VARCHAR(20),
	Email VARCHAR(50)
);

CREATE TABLE Invoices
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	InvoceNo VARCHAR(40) NOT NULL,
	ClientId INT NOT NULL,
	CreateDate DATE NOT NULL,
	FOREIGN KEY(ClientId) REFERENCES Clients(Id)
);

CREATE TABLE InvoiceItems
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	InvoceId INT NOT NULL,
	ProductId INT NOT NULL,
	Quantity INT NOT NULL,
	FOREIGN KEY(InvoceId) REFERENCES Invoices(Id),
	FOREIGN KEY(ProductId) REFERENCES Products(Id)
);